require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DefaultMessagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DefaultMessage. As you add validations to DefaultMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DefaultMessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all default_messages as @default_messages" do
      default_message = DefaultMessage.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:default_messages)).to eq([default_message])
    end
  end

  describe "GET #show" do
    it "assigns the requested default_message as @default_message" do
      default_message = DefaultMessage.create! valid_attributes
      get :show, params: {id: default_message.to_param}, session: valid_session
      expect(assigns(:default_message)).to eq(default_message)
    end
  end

  describe "GET #new" do
    it "assigns a new default_message as @default_message" do
      get :new, params: {}, session: valid_session
      expect(assigns(:default_message)).to be_a_new(DefaultMessage)
    end
  end

  describe "GET #edit" do
    it "assigns the requested default_message as @default_message" do
      default_message = DefaultMessage.create! valid_attributes
      get :edit, params: {id: default_message.to_param}, session: valid_session
      expect(assigns(:default_message)).to eq(default_message)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DefaultMessage" do
        expect {
          post :create, params: {default_message: valid_attributes}, session: valid_session
        }.to change(DefaultMessage, :count).by(1)
      end

      it "assigns a newly created default_message as @default_message" do
        post :create, params: {default_message: valid_attributes}, session: valid_session
        expect(assigns(:default_message)).to be_a(DefaultMessage)
        expect(assigns(:default_message)).to be_persisted
      end

      it "redirects to the created default_message" do
        post :create, params: {default_message: valid_attributes}, session: valid_session
        expect(response).to redirect_to(DefaultMessage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved default_message as @default_message" do
        post :create, params: {default_message: invalid_attributes}, session: valid_session
        expect(assigns(:default_message)).to be_a_new(DefaultMessage)
      end

      it "re-renders the 'new' template" do
        post :create, params: {default_message: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested default_message" do
        default_message = DefaultMessage.create! valid_attributes
        put :update, params: {id: default_message.to_param, default_message: new_attributes}, session: valid_session
        default_message.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested default_message as @default_message" do
        default_message = DefaultMessage.create! valid_attributes
        put :update, params: {id: default_message.to_param, default_message: valid_attributes}, session: valid_session
        expect(assigns(:default_message)).to eq(default_message)
      end

      it "redirects to the default_message" do
        default_message = DefaultMessage.create! valid_attributes
        put :update, params: {id: default_message.to_param, default_message: valid_attributes}, session: valid_session
        expect(response).to redirect_to(default_message)
      end
    end

    context "with invalid params" do
      it "assigns the default_message as @default_message" do
        default_message = DefaultMessage.create! valid_attributes
        put :update, params: {id: default_message.to_param, default_message: invalid_attributes}, session: valid_session
        expect(assigns(:default_message)).to eq(default_message)
      end

      it "re-renders the 'edit' template" do
        default_message = DefaultMessage.create! valid_attributes
        put :update, params: {id: default_message.to_param, default_message: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested default_message" do
      default_message = DefaultMessage.create! valid_attributes
      expect {
        delete :destroy, params: {id: default_message.to_param}, session: valid_session
      }.to change(DefaultMessage, :count).by(-1)
    end

    it "redirects to the default_messages list" do
      default_message = DefaultMessage.create! valid_attributes
      delete :destroy, params: {id: default_message.to_param}, session: valid_session
      expect(response).to redirect_to(default_messages_url)
    end
  end

end
